// import functions and grab DOM elements

// let state

// set event listeners
// get user input
// use user input to update state
// update DOM to reflect the new state


//grabbing the DOM elements:
// all three cup buttons
const cupBtnOne = document.getElementById('cup-btn-1');
const cupBtnTwo = document.getElementById('cup-btn-2');
const cupBtnThree = document.getElementById('cup-btn-3');
// all three cup images
const cupImgOne = document.getElementById('cup-img-1');
const cupImgTwo = document.getElementById('cup-img-2');
const cupImgThree = document.getElementById('cup-img-3');
// all possible ball locations in an array
const hidingPlaces = ['cupOne', 'cupTwo', 'cupThree'];
// total wins and total guesses
const winsEl = document.getElementById('wins');
const totalEl = document.getElementById('total');
// starting values for wins and total guesses
let correctGuesses = 0;
let totalGuesses = 0;
// grabbing reset button DOM element
const resetButton = document.getElementById('reset-button');

/* 
function for randomly assigning kitten-cup image to one of the three cups
*/

function randomCup() {
  const hidingSpot = Math.floor(Math.random() * hidingPlaces.length);
  const answer = hidingPlaces[hidingSpot];
  return answer;
}

/* 
event listeners for each cup button,
randomly selects a cup to hide the ball in on user click
*/
cupBtnOne.addEventListener('click', () => {
  handleGuess(randomCup(), 'cupOne');
});

cupBtnTwo.addEventListener('click', () => {
  handleGuess(randomCup(), 'cupTwo');
});

cupBtnThree.addEventListener('click', () => {
  handleGuess(randomCup(), 'cupThree');
});

/*
function to update the DOM to reflect the new state
generated by the user's guess
*/
function handleGuess(correctSpot, userGuess) {

  clearScreen();

  if (correctSpot === userGuess) {
    correctGuesses++;
    totalGuesses++;
    winsEl.textContent = correctGuesses;
  } else {
    totalGuesses++;
  }

  if (correctSpot === 'cupOne') {
    cupImgOne.src = './assets/teacup-kitten.png';
  } else if (correctSpot === 'cupTwo') {
    cupImgTwo.src = './assets/teacup-kitten.png';
  } else {
    cupImgThree.src = './assets/teacup-kitten.png';
  }

  totalEl.textContent = totalGuesses;
}

// event listener for reset button
resetButton.addEventListener('click', () => {
  winsEl.textContent = 0;
  totalEl.textContent = 0;
  clearScreen();
});

// function to restore cup images to default state 
function clearScreen() {
  cupImgOne.src = './assets/fancy-teacup.png';
  cupImgTwo.src = './assets/fancy-teacup.png';
  cupImgThree.src = './assets/fancy-teacup.png';
}
